[versions]
# plugins
lombokPlugin = "8.14"
shadow = "9.0.0-rc3"
slimjar = "2.1.8"
runPaper = "2.3.1"

# libs
lombok = "1.18.22"
spigot = "1.21.11-R0.1-SNAPSHOT"
placeholderApi = "2.11.6"
packetevents = "2.11.2"
adventure = "4.25.0"
undertow = "2.2.17.Final"
semVer = "0.7.2"
commons-io = "2.14.0"
commons-imaging = "1.0.0-alpha6"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
placeholderApi = { module = "me.clip:placeholderapi", version.ref = "placeholderApi" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventure-nbt = { module = "net.kyori:adventure-nbt", version.ref = "adventure" }
undertow = { module = "io.undertow:undertow-core", version.ref = "undertow" }
semver = { module = "com.github.zafarkhaja:java-semver", version.ref = "semVer" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-imaging = { module = "org.apache.commons:commons-imaging", version.ref = "commons-imaging" }

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombokPlugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
slimjar = { id = "de.crazydev22.slimjar", version.ref = "slimjar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
